### PR TITLE
v1.11.1

### PR DESCRIPTION
**Pull request by mtsolmn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by MatthieuDartiailh** [comment]
@mtsolmn there is already a PR (https://github.com/conda-forge/pyvisa-feedstock/pull/20) but it is stuck on a weird Windows only failure.

**Comment by mtsolmn** [comment]
@MatthieuDartiailh yes I know, but I can't make commits to it. I was trying help fix these windows failures but couldn't figure it out myself. I believe it is a problem with the LIEF module in conda-build, so it might be an external issue. I asked the conda admins on https://gitter.im/conda-forge/conda-forge.github.io last night but didn't get a response

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
Fixed with #26

**Pull request closed without merging**
