### PR TITLE
add missing entry points to recipe

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Pyvisa includes 2 shell program that were not properly packaged so far. This PR add them and add test for them.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin, please rerender

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin please rerender

**Comment by MatthieuDartiailh** [comment]
Closes https://github.com/pyvisa/pyvisa-py/issues/229

**Comment by MatthieuDartiailh** [comment]
This is good to go from my end. The first person to review can merge if there is no issue.

**Comment by cjermain** [comment]
Thanks @MatthieuDartiailh!

**Comment by bilderbuchi** [comment]
Thanks @cjermain @MatthieuDartiailh, I confirm this fixes the issue.

**Pull request merged**
