### PR TITLE
updated v1.9.1

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
- use pip and host section rather than build
Try to start fresh since the other PR looks kind of broken ...

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin please rerender

**Comment by MatthieuDartiailh** [comment]
Starting over did the trick. Feel free to merge if you are ok with it @basnijholt.

**Review by basnijholt — APPROVED** [review]

**Comment by basnijholt** [comment]
LGTM! I have no rights to merge, so please go ahead ;-)

**Comment by MatthieuDartiailh** [comment]
Thanks @basnijholt

**Pull request merged**
