### PR TITLE
update recipe for PyVISA 1.9.0

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
I would also like to be added to the recipe maintainers.

### CODE REVIEW

**Comment by melund** [comment]
@conda-forge-admin, please rerender

**Comment by melund** [comment]
This may fail because PyVISA starts with a capital P... Can you try replacing the template with this:
```
https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
```

**Comment by melund** [comment]
@MatthieuDartiailh Only the two first must be lowercase. Not the actual file name.

**Comment by MatthieuDartiailh** [comment]
Done

**Comment by MatthieuDartiailh** [comment]
conda-forge-admin, please rerender

**Comment by melund** [comment]
@conda-forge-admin, please rerender

**Comment by melund** [comment]
@MatthieuDartiailh. It must start with a `@`.  You can see the available commands here: 
https://conda-forge.org/docs/webservice.html

**Comment by MatthieuDartiailh** [comment]
I know it but I went too fast sorry about the noise.

**Pull request merged**
