### PR TITLE
pyvisa v1.11.1

### PR DESCRIPTION
**Pull request by mtsolmn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@conda-forge/lief there appears to be lief module related issues from conda-build when packaging for windows. I have been unable to resolve this problem and some help would be greatly appreciated. Thanks!

For _win_64_python3.7.____cpython_ and _win_64_python3.8.____cpython_:
```
File "C:\Miniconda\lib\site-packages\conda_build\os_utils\liefldd.py", line 511, in get_linkages
    sysroot=sysroot, envroot=envroot, arch=arch)
  File "C:\Miniconda\lib\site-packages\conda_build\os_utils\liefldd.py", line 401, in inspect_linkages_lief
    binary = lief.parse(filename)
lief.read_out_of_bound: Try to read 0x60 bytes from 0x1a (7a) which is bigger than the binary's size
```

For _win_64_python3.6.____cpython_:
```
File "C:\Miniconda\lib\site-packages\conda_build\os_utils\liefldd.py", line 406, in inspect_linkages_lief
    if binary.format == lief.EXE_FORMATS.ELF:
AttributeError: 'NoneType' object has no attribute 'format'
```

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by MatthieuDartiailh** [comment]
Obsokete after the merging of #26

**Pull request closed without merging**
